[design/#82] 문서 카드, 모달 UI 수정
2023WB-TeamB/Frontend pull request #85
Opened 2024-01-20 15:47 UTC by hoon99

## 📢 기능 설명

- [ ]  캐러셀 카드, 모달 UI 수정
- [ ] 갤러리 모달 -> 프리뷰로 교체(문서 상세조회 연동)

추후 업데이트 사항

- 캐러셀 카드에 레포 이름 띄우기
- 모달/프리뷰에 태그 추가
- 모달/프리뷰 UI 수정

필요시 실행결과 스크린샷 첨부
<img width="1415" alt="image" src="https://github.com/2023WB-TeamB/Frontend/assets/79782580/cdbff58c-fb1f-498b-b793-75379fb20142">
![image](https://github.com/2023WB-TeamB/Frontend/assets/79782580/b9bf1650-33e2-4104-8b6f-9b130a7aff6c)
<br>

## 연결된 issue

연결된 issue를 자동을 닫기 위해 아래 {이슈넘버}를 입력해주세요. <br>
close #{이슈넘버}
<br>

## ✅ 체크리스트

- [ ] PR 제목 규칙 잘 지켰는가?
- [ ] 추가/수정사항을 설명하였는가?
- [ ] 이슈넘버를 적었는가?

2024-01-20 17:44 UTC, naGGuri requested changes
URL 형식만 한번 확인해주시면 문제없을거 같아요!

2024-01-20 17:44 UTC, naGGuri commented on src/pages/MyDocsPage.tsx
이부분 확인해보니까 수정하고 나서는 url양식이 틀린지 api호출에 실패합니다
![스크린샷 2024-01-21 오전 2 29 21](https://github.com/2023WB-TeamB/Frontend/assets/111751838/94158e4a-22b8-4dd5-8ebb-c18593f5f959)
![스크린샷 2024-01-21 오전 2 30 04](https://github.com/2023WB-TeamB/Frontend/assets/111751838/f0aa8b9e-f824-4ae7-b2d3-f3d0a28c605f)

![스크린샷 2024-01-21 오전 2 29 54](https://github.com/2023WB-TeamB/Frontend/assets/111751838/66b97cb8-cac6-4a0c-8c95-d83a37461ca7)

위 사진과 같이 수정하니까 api호출이 정상적으로 작동해요

2024-01-20 17:44 UTC, naGGuri commented on src/components/mydocs/lower/getContent.tsx
url 수정이 필요해보입니다

2024-01-20 17:44 UTC, naGGuri commented on src/components/mydocs/lower/PreviewContent.tsx
프리뷰 콘텐츠에서 콘텐츠 내용이 레이아웃을 넘어서면 '...'으로 표현하는건 어떨까요!?

2024-01-21 05:28 UTC, hoon99 commented on src/components/mydocs/lower/PreviewContent.tsx
넵 오늘 UI 수정하면서 반영하겠습니다

2024-01-21 06:37 UTC, naGGuri approved these changes

2024-01-21 06:52 UTC, merged